### ISSUE TITLE
Aliasing a Box is undefined behavior

### ISSUE THREAD

**Issue by b05902132** [JP-Ellis/rust-skiplist#14]
Well this sucks, but it seems that you may not alias a `Box`.

https://github.com/jonhoo/left-right/issues/74

I believe this means you cannot store a `Box` and a pointer to the box content. You will need to call `Box::into_raw` before putting it into a SkipNode.

If you are too busy to fix that, I'm currently planning to rewrite this library as an exercise. All unsafe code will reside in `skipnode.rs`. But I cannot guarantee the quality of my code 😅

**Comment by JP-Ellis** [comment]
I'm happy to accept PR requests.  If it is going to be a pretty large rewrite, I can add you as a contributor and you can create a new branch?

**Comment by b05902132** [comment]
Yes, it will be a pretty large rewrite.

This is my rewrite on SkipNode and SkipList: https://github.com/b05902132/rust-skiplist/tree/rewrite

The code is not as well commented as yours; I wasn't expecting to publish the code.

**Comment by JP-Ellis** [comment]
Yeah, I tried to keep it well commented given how much unsafe code I was using.

I would welcome a big PR if it means getting rid of this undefined behaviour and simplifying the code.  You can either work in a draft PR, or I'm happy for you to be added as a contributor and you can create a new branch to work on.  Let me know which you would prefer.

**Comment by b05902132** [comment]
Sorry, but I'm pretty new to the open source world; what's the difference?

I guess if you add me as a contributor I can add Miri to detect UB in your CI.
