### ISSUE TITLE
How do i get a mutable reference of elements.

### ISSUE THREAD

**Issue by yihuang** [JP-Ellis/rust-skiplist#7]
Do we have to implement all kinds of ``mut`` version of operations, ``IndexMut``, ``front_mut``, ``back_mut``, etc?

**Comment by JP-Ellis** [comment]
These are implemented for types where it is sensible to do so.  In particular, a few parts of this crate expect things to be ordered, thus providing mutable references to items would be a very bad idea as it might break the ordering.

If you *really* must, use a [`Cell` or `RefCell`](https://doc.rust-lang.org/std/cell/index.html), but I would be extremely careful about doing so.
